<<<<<<< HEAD
import './globals.css'

export const metadata = {
  title: 'Kitch',
  description: 'Generated by create next app',
}
=======
import "styles/globals.css";
import { MainAppBar } from "../Components/MainAppBar";
import NavigationLive from "../Components/NaviguationLive";

export const metadata = {
  title: "Kitch",
  description: "Clone de Twitch mais en version Kitch",
};
>>>>>>> df09780d0d8b090ee3e474694e443d3da0ff9af8

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <body>{children}</body>
=======
    <html lang="fr">
      <body>
        <MainAppBar />
        <NavigationLive />
        {children}
      </body>
>>>>>>> df09780d0d8b090ee3e474694e443d3da0ff9af8
    </html>
  );
}
